name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
  workflow_dispatch:

jobs:
  skip-check:
    if: contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.skip.outputs.should-skip }}
    steps:
      - uses: actions/checkout@v4
      - id: skip
        uses: ./.github/actions/skip

  build-test:
    needs: skip-check
    if: needs.skip-check.outputs.should-skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - uses: actions/upload-artifact@v4
        with:
          name: "Tests bin folder"
          path: "TrailingCommaAnalyzer.Test/bin/"
      - uses: ./.github/actions/test

  check:
    needs: skip-check
    if: needs.skip-check.outputs.should-skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check
